import { Inter } from "next/font/google";
import "../app/Styles/globals.css";
import Sidebar from '../components/NavBar/index';
import styles from './Styles/page.module.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className={styles.container}>
          <Sidebar />
          <main className={inter.className}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
